server:
  port: 8080
spring:
  application:
    name: uaa-security-started
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:test}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      #      hibernate.generate_statistics: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      # 解决springboot2.x默认MyISAM的逻辑
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: localhost
    port: 6379
    #    password: localhost
    timeout: 6000
    lettuce:
      pool:
        max-active: 5000 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 2000 # 连接池中的最大空闲连接
## 指定Security配置类
security:
  started:
    session:
      share
    chapter:
      logout-process



